-- ============================================================================
-- 126 - Las cuentas de cada ruta y la trazabilidad de lo que entra a ellas
-- ============================================================================
-- LO QUE SE PIDIO
-- "Agregar a la configuración de cada ruta qué números de cuenta tiene
--  asociados, para que de ahí salga el selector del módulo de pagos y llevar
--  trazabilidad de los pagos a cuentas."
--
-- LO QUE HABIA
-- ------------
-- La tabla `cuentas` (id, ruta, nombre, cuenta) existe desde antes del repo
-- (ver 000) y el selector de ventas ya la lee, pero NO habia pantalla para
-- cargarla: las cuentas se metian a mano en Supabase. Y desde el script 125
-- cada pago por transferencia guarda su `cuenta_id` en `gestiones.detalle`.
--
-- LO QUE HACE ESTE SCRIPT
-- -----------------------
--   PASO 2-4  `activa`, `titular` y `created_at` en `cuentas`. Una cuenta NO
--             se borra: tiene pagos y ventas apuntandole. Se DESACTIVA, y deja
--             de salir en los selectores, pero su historia queda.
--   PASO 5    Que el `id` se genere solo. La tabla vino de afuera con un
--             BIGINT sin secuencia: un INSERT desde la app fallaria por id
--             nulo. Se le pone IDENTITY arrancando despues del id mas alto.
--   PASO 6    Permisos para que Configuracion pueda crear y editar cuentas.
--   PASO 7    `v_pagos_por_cuenta`: un renglon por cada peso que entro a una
--             cuenta. Una reversa aparece con el monto en negativo y la
--             cuenta del pago que reversa, asi la suma siempre es la neta.
--
-- Corre los pasos EN ORDEN. Los pasos 1, 8 y 9 no escriben nada.
-- ============================================================================


-- ── PASO 1) Como esta hoy (SOLO LECTURA) ────────────────────────────────
SELECT c.*, (SELECT count(*) FROM loans l WHERE l.cuenta_id = c.id) AS ventas_con_esta_cuenta
  FROM cuentas c
 ORDER BY c.ruta, c.id;


-- ── PASO 2) Activa / inactiva ───────────────────────────────────────────
ALTER TABLE public.cuentas ADD COLUMN IF NOT EXISTS activa BOOLEAN NOT NULL DEFAULT true;


-- ── PASO 3) A nombre de quien esta ──────────────────────────────────────
ALTER TABLE public.cuentas ADD COLUMN IF NOT EXISTS titular TEXT;


-- ── PASO 4) Desde cuando existe ─────────────────────────────────────────
ALTER TABLE public.cuentas ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();


-- ── PASO 5) Que el id se genere solo ────────────────────────────────────
-- Si ya tiene secuencia o identity, no se toca.
DO $id$
DECLARE
  v_identity "char";
  v_default  text;
  v_max      bigint;
BEGIN
  SELECT a.attidentity, pg_get_expr(d.adbin, d.adrelid)
    INTO v_identity, v_default
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
   WHERE a.attrelid = 'public.cuentas'::regclass AND a.attname = 'id';

  IF v_identity IN ('a', 'd') OR v_default IS NOT NULL THEN
    RAISE NOTICE 'cuentas.id ya se genera solo (%): no se toca.', COALESCE(v_default, 'identity');
    RETURN;
  END IF;

  SELECT COALESCE(max(id), 0) + 1 INTO v_max FROM public.cuentas;
  EXECUTE format(
    'ALTER TABLE public.cuentas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    v_max);
  RAISE NOTICE 'cuentas.id ahora es IDENTITY, arranca en %', v_max;
END
$id$;


-- ── PASO 6) Permisos para Configuracion ─────────────────────────────────
-- (RLS no existe en esta base: el filtro por ruta es de la app.)
DO $perm$
DECLARE
  v_seq text := pg_get_serial_sequence('public.cuentas', 'id');
BEGIN
  GRANT SELECT, INSERT, UPDATE ON public.cuentas TO anon, authenticated;
  IF v_seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', v_seq);
  END IF;
END
$perm$;


-- ── PASO 7) La trazabilidad: lo que entro a cada cuenta ─────────────────
-- Solo eventos APLICADOS del libro. La reversa no trae la cuenta en su
-- detalle: se toma la del pago que reversa, con el monto en negativo.
CREATE OR REPLACE VIEW public.v_pagos_por_cuenta AS
SELECT g.id                                   AS gestion_id,
       COALESCE(g.detalle->>'cuenta_id', ref.detalle->>'cuenta_id')::bigint AS cuenta_id,
       g.ruta,
       g.fecha_gestion,
       g.fecha_hora,
       g.tipo,
       CASE WHEN g.tipo = 'reversa' THEN -g.monto ELSE g.monto END AS monto,
       g.loan_id,
       g.client_id,
       cl.apodo,
       cl.nombre_completo,
       g.user_id,
       COALESCE(g.detalle->>'foto_url', ref.detalle->>'foto_url') AS foto_url,
       g.observacion
  FROM public.gestiones g
  LEFT JOIN public.gestiones ref ON ref.id = g.referencia_gestion_id
  LEFT JOIN public.clients cl    ON cl.id  = g.client_id
 WHERE g.estado = 'aplicada'
   AND g.tipo IN ('pago', 'cancelacion', 'abono_venta', 'reversa')
   AND COALESCE(g.detalle->>'cuenta_id', ref.detalle->>'cuenta_id') IS NOT NULL;

GRANT SELECT ON public.v_pagos_por_cuenta TO anon, authenticated;


-- ── PASO 8) Que quedo bien (SOLO LECTURA) ───────────────────────────────
-- `id_automatico` tiene que decir `t`.
SELECT (SELECT attidentity IN ('a','d') OR EXISTS (
          SELECT 1 FROM pg_attrdef d WHERE d.adrelid = a.attrelid AND d.adnum = a.attnum)
          FROM pg_attribute a
         WHERE a.attrelid = 'public.cuentas'::regclass AND a.attname = 'id') AS id_automatico,
       (SELECT count(*) FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'cuentas'
           AND column_name IN ('activa', 'titular', 'created_at'))      AS columnas_nuevas_de_3,
       (SELECT count(*) FROM public.v_pagos_por_cuenta)                 AS pagos_con_cuenta;


-- ── PASO 9) Lo recibido por cuenta en los ultimos 30 dias (SOLO LECTURA) ─
SELECT c.ruta, c.nombre, c.cuenta, c.activa,
       count(v.gestion_id)        AS pagos,
       COALESCE(sum(v.monto), 0)  AS recibido
  FROM public.cuentas c
  LEFT JOIN public.v_pagos_por_cuenta v
         ON v.cuenta_id = c.id AND v.fecha_gestion >= current_date - 30
 GROUP BY c.id, c.ruta, c.nombre, c.cuenta, c.activa
 ORDER BY c.ruta, c.nombre;
